<?php

namespace JS\DefaultBundle\Repository;

use Doctrine\ORM\EntityRepository;
use JS\DefaultBundle\Repository\BaseRepository;

/**
 * CaruselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends BaseRepository
{
    public function findAllOrderedByName()
    {
        $qb = $this->createQueryBuilder('a')
            ->orderBy('a.name', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
