<?php

namespace JS\DefaultBundle\Repository;

use Doctrine\ORM\EntityRepository;
use JS\DefaultBundle\Repository\BaseRepository;

/**
 * CaruselRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends BaseRepository
{
    public function findAllOrderedByName()
    {
        $qb = $this->createQueryBuilder('c')
            ->orderBy('c.name', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function findAllOrderedByNameWithoutHidden()
    {
        $qb = $this->createQueryBuilder('c')
            ->join('c.products', 'p')
            ->andWhere('p.isHidden = false')
            ->orderBy('c.name', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
