<?php

namespace JS\DefaultBundle\Repository;

use Doctrine\ORM\EntityRepository;
use JS\DefaultBundle\Repository\BaseRepository;

/**
 * OrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OrderRepository extends BaseRepository
{
    public function findLastOrders( $limit = null )
    {
        $qb = $this->createQueryBuilder('o')
            ->orderBy('o.createdAt', 'DESC');
        if($limit)
            $qb->setMaxResults( $limit );
        return $qb->getQuery()->getResult();
    }
}
