<?php

namespace JS\DefaultBundle\Repository;

use Doctrine\ORM\EntityRepository;
use JS\DefaultBundle\Repository\BaseRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends BaseRepository
{
}
